### PR TITLE
feat: crowdin updating

### PR DESCRIPTION
**Pull request by JoeKarow**
# Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

Issue Number: IN-920

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

### CODE REVIEW

**Comment by JoeKarow** [comment]
@SocketSecurity ignore npm/core-js@3.37.0

**Comment by JoeKarow** [comment]
@socket-security ignore npm/core-js@3.37.0

**Comment by JoeKarow** [comment]
@socket-security ignore npm/core-js@3.37.0

**Comment by JoeKarow** [comment]
@coderabbitai resolve

**Review by InReach-svc — APPROVED** [review]

**Pull request merged**
